import React from "react";
import Navbar from "../Navbar";


export const GalleryData = [
  {
    id: 1,
    title: "2x2",
    des: "Meilong 2x2",
    price: 214,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/meilong2x2.jpg"
  },
  {
    id: 2,
    title: "3x3",
    des: "Moyu WRM",
    price: 214,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/wrm.jpg",
  },
  {
    id: 3,
    title: "4x4",
    des:"Meilong 4x4",
    price:800,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/meilong4.jpg",
  },
  {
    id: 4,
    title: "5x5",
    des: "Yuxin Little Magic 5",
    price: 234,
    info:"Manufacturer: YUXIN",
    image: "../public/rubiks/ylm5x5.jpg",
  },
  {
    id: 5,
    title: "6x6",
    des: "MGC 6X6",
    price: 234,
    info:"Manufacturer: MGC",
    image: "../public/rubiks/mgc6x6.jpg",
  },
  {
    id: 6,
    title: "7x7",
    des: "Meilong 7x7",
    price: 234,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/meilong7x7.jpg",
  },
  {
    id: 7,
    title: "Others",
    des: "Fidget Spinner",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/fidget.jpg",
  },
  {
    id: 8,
    title: "Others",
    des: "Qiyi Gear Cube",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/gear.jpg",
  },
  {
    id: 9,
    title: "Others",
    des: "3x3 KeyChain",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/keychain3x3.jpg",
  },
  {
    id: 10,
    title: "Others",
    des: "Ivy KeyChain",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/keychainivy.jpg",
  },
  {
    id: 11,
    title: "Others",
    des: "Pyraminx KeyChain",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/keychainpyra.jpg",
  },
  {
    id: 12,
    title: "Others",
    des: "Kilominx",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/kilominx.jpg",
  },
  {
    id: 13,
    title: "Others",
    des: "Klotski 15",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/klotsky15.jpg",
  },
  {
    id: 14,
    title: "Others",
    des: "Klotski 24",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/klotsky24.jpg",
  },
  {
    id: 15,
    title: "Timer",
    des: "Qiyi Black Timer",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/qiyitimer.jpg",
  },
  {
    id: 16,
    title: "Pyraminx",
    des: "Meilong Pyraminx",
    price: 234,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/meilongpyra.jpg",
  },
  {
    id: 17,
    title: "Others",
    des: "Qiyi Pie",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/pie.jpg",
  },
  {
    id: 18,
    title: "Megaminx",
    des: "Qiyi Megaminx",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/qiyimegaminx.jpg",
  },
  {
    id: 19,
    title: "5x5",
    des: "Qiyi Ms 5X5",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/qiyims5x5.jpg",
  },
  {
    id: 20,
    title: "2x2",
    des: "Moyu RS2M",
    price: 234,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/rs2m.jpg",
  },
  {
    id: 21,
    title: "3x3",
    des: "Moyu RS3M",
    price: 234,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/rs3m.jpg",
  },
  {
    id: 22,
    title: "4x4",
    des: "Moyu RS4M",
    price: 234,
    info:"Manufacturer: MOYU",
    image: "../public/rubiks/rs4m.jpg",
  },
  {
    id: 23,
    title: "3x3",
    des: "Tornado v3",
    price: 234,
    info:"Manufacturer: QIYI",
    image: "../public/rubiks/tornadov3.jpg",
  },
  {
    id: 24,
    title: "2x2",
    des: "YJ 2X2",
    price: 234,
    info:"Manufacturer: YJ",
    image: "../public/rubiks/yj 2x2.jpg",
  },
  {
    id: 25,
    title: "Megaminx",
    des: "Yuxin Little Magic Megaminx",
    price: 234,
    info:"Manufacturer: YUXIN",
    image: "../public/rubiks/ylmmegaminx.jpg",
  },
  {
    id: 26,
    title: "Others",
    des: "Yuxin Little Magic Skewb",
    price: 234,
    info:"Manufacturer: Yuxin",
    image: "../public/rubiks/ylmskewb.jpg",
  },
  {
    id: 27,
    title: "4x4",
    des: "Yuxin 4x4",
    price: 234,
    info:"Manufacturer: Yuxin",
    image: "../public/rubiks/yuxin4x4.jpg",
  },
  {
    id: 28,
    title: "5x5",
    des: "Yuxin 5x5",
    price: 234,
    info:"Manufacturer: Yuxin",
    image: "../public/rubiks/yuxin5x5.jpg",
  },
  {
    id: 29,
    title: "Pyraminx",
    des: "Yuxin Pyraminx",
    price: 234,
    info:"Manufacturer: Yuxin",
    image: "../public/rubiks/yuxinpyra.jpg",
  }

];